# Generated by Django 5.0.6 on 2024-11-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_images/'),
        ),
    ]
